#!/bin/bash
((php script.php | grep \'0\'\) | shuf | sed 's/\x270\x27);//g') && (php script.php | grep \'1\'\) | shuf | sed 's/\x271\x27);//g') &&  (php script.php | grep \'2\'\) | shuf |sed 's/\x272\x27);//g')) | awk '{if (NR == 1) a = -1; if (((NR - 1)%5) == 0) a = a + 1; print $1 " "  $2 " " $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 "\x27"a"\x27);"}'

